# Этот файл разворачивает MongoDB и веб-интерфейс Mongo-Express

services:
  # Сервис MongoDB (база данных)
  mongo:
    image: mongo:latest          # Официальный образ MongoDB
    container_name: mongodb      # Явное имя контейнера
    restart: unless-stopped      # Автоперезапуск (кроме ручной остановки)
    ports:
      - "27017:27017"            # Проброс порта наружу
    environment:
      MONGO_INITDB_ROOT_USERNAME: SaqurDB      # Суперпользователь
      MONGO_INITDB_ROOT_PASSWORD: root   # Пароль (ЗАМЕНИТЕ в продакшене!)
    volumes:
      - mongodb_data:/data/db    # Сохранение данных между перезапусками

  # Веб-интерфейс для управления MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"              # Веб-интерфейс на http://localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: SaqurDB      # Логин для подключения
      ME_CONFIG_MONGODB_ADMINPASSWORD: root   # Пароль (должен совпадать с MongoDB)
      ME_CONFIG_MONGODB_URL: mongodb://SaqurDB:root@mongodb:27017/
    depends_on:
      - mongo                    # Ждёт запуска MongoDB

# Определяем том для хранения данных
volumes:
  mongodb_data:

# docker-compose up -d
# ocker-compose down -v